version: '3.2'

services:
  flask_app:
    build:
      context: '../'
      dockerfile: 'docker/flask/Dockerfile'
    container_name: flask_app
    labels:
     - "traefik.port=8000"
     - "traefik.enable=true"
     - "traefik.frontend.rule=Host:example.com"
     - "traefik.docker.network=web"
    volumes:
      - ../:/app/
    restart: always
    networks:
      - web

networks:
  web: 
    external: true