version: '3.2'

services:
  flask_app:
    build:
      context: '../'
      dockerfile: 'docker/flask/Dockerfile'
    container_name: flask_app
    labels:
     - "traefik.port=8000"
     - "traefik.enable=true"
     - "traefik.frontend.rule=Host:example.com"
     - "traefik.docker.network=web"
    volumes:
      - ../:/app/
    restart: always
    networks:
      - web

  reverse-proxy:
    image: traefik:v2.0
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - ./traefik.toml:/etc/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - web

networks:
  web: 
    external: true