version: '3.2'

services:
  photobooth_webapp:
    build:
      context: '../'
      dockerfile: 'docker/flask/Dockerfile'
    container_name: photobooth_webapp
    expose:
      - "5000"
    ports:
      - 80:5000
    volumes:
      - ../webapp/:/app/
      - ../_tmp/:/app/_tmp
    restart: always
