version: '3.2'

services:
  reverse-proxy:
    image: traefik:v2.0
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - traefik.toml:/etc/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - web

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  web:
    external: true